#!/usr/bin/env python3
"""Fetch ColdIQ marketplace provider logos into public/gtm/marketplace/."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "public" / "gtm" / "marketplace"
MANIFEST_TS = ROOT / "lib" / "coldiqMarketplace.ts"
LISTING_URL = "https://coldiq.com/marketplace/apis"
USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"

CAREER_PLACEHOLDER_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#4a6fa8" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
  <rect x="2" y="7" width="20" height="14" rx="2"/>
  <path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2"/>
</svg>
"""


def fetch(url: str) -> bytes:
    req = Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urlopen(req, timeout=30) as resp:
            return resp.read()
    except HTTPError as exc:
        # Google favicons may return 404 with a default icon body.
        body = exc.read()
        if body:
            return body
        raise


def fetch_text(url: str) -> str:
    return fetch(url).decode("utf-8", "replace")


def classify_logo(url: str) -> str:
    if "/images/providers/" in url:
        return "coldiq-hosted"
    if "framerusercontent.com" in url:
        return "framer"
    if "favicons" in url:
        return "favicon"
    return "external"


def normalize_source_url(raw: str) -> str:
    url = unquote(raw)
    if url.startswith("/"):
        return f"https://coldiq.com{url}"
    return url


def upgrade_favicon(url: str) -> str:
    if "favicons" not in url:
        return url
    return re.sub(r"sz=\d+", "sz=128", url)


def ext_for_url(url: str) -> str:
    path = urlparse(url).path.lower()
    if path.endswith(".svg"):
        return "svg"
    if path.endswith(".webp"):
        return "webp"
    if path.endswith(".jpg") or path.endswith(".jpeg"):
        return "jpg"
    return "png"


def parse_providers(html: str) -> list[dict]:
    parts = re.split(r'href="/marketplace/apis/([^"]+)"', html)
    providers: list[dict] = []
    seen: set[str] = set()

    for i in range(1, len(parts), 2):
        slug = parts[i]
        if slug in seen:
            continue
        seen.add(slug)
        chunk = parts[i + 1][:5000]
        name_match = re.search(r"<h3[^>]*>([^<]+)</h3>", chunk)
        image_match = re.search(r"/_next/image\?url=([^\"'&]+)", chunk)
        external_match = re.search(
            r"(https://[^\"']+logo[^\"']*\.svg)", chunk, re.IGNORECASE
        )
        framer_match = re.search(
            r"(https://framerusercontent.com/images/[^\"'?&]+)", chunk
        )
        provider_match = re.search(r"(/images/providers/[^\"'?&]+)", chunk)

        source_url = None
        if provider_match:
            source_url = normalize_source_url(provider_match.group(1))
        elif framer_match:
            source_url = framer_match.group(1)
        elif external_match:
            source_url = external_match.group(1)
        elif image_match:
            source_url = normalize_source_url(unquote(image_match.group(1)))

        domain = None
        if source_url and "domain=" in source_url:
            domain_match = re.search(r"domain=([^&]+)", source_url)
            if domain_match:
                domain = domain_match.group(1)

        providers.append(
            {
                "slug": slug,
                "name": name_match.group(1) if name_match else slug,
                "domain": domain,
                "sourceUrl": source_url,
                "logoType": classify_logo(source_url) if source_url else None,
            }
        )

    return providers


def write_manifest(providers: list[dict]) -> None:
    lines = [
        "// Generated by scripts/fetch_coldiq_logos.py — do not edit by hand.",
        "",
        "export type ColdiqLogoType =",
        '  | "favicon"',
        '  | "coldiq-hosted"',
        '  | "framer"',
        '  | "external";',
        "",
        "export type ColdiqProvider = {",
        "  slug: string;",
        "  name: string;",
        "  domain: string | null;",
        "  logoFile: string;",
        "  logoType: ColdiqLogoType;",
        "  sourceUrl: string;",
        "  isPlaceholder?: boolean;",
        "};",
        "",
        "export const COLDIQ_MARKETPLACE_PROVIDERS = [",
    ]

    for provider in providers:
        lines.append("  {")
        lines.append(f'    slug: {json.dumps(provider["slug"])},')
        lines.append(f'    name: {json.dumps(provider["name"])},')
        lines.append(
            f'    domain: {json.dumps(provider["domain"])},'
            if provider["domain"]
            else "    domain: null,"
        )
        lines.append(f'    logoFile: {json.dumps(provider["logoFile"])},')
        lines.append(f'    logoType: {json.dumps(provider["logoType"])},')
        lines.append(f'    sourceUrl: {json.dumps(provider["sourceUrl"])},')
        if provider.get("isPlaceholder"):
            lines.append("    isPlaceholder: true,")
        lines.append("  },")

    lines.extend(
        [
            "] as const satisfies readonly ColdiqProvider[];",
            "",
            "export const COLDIQ_MARKETPLACE_SLUGS = COLDIQ_MARKETPLACE_PROVIDERS.map(",
            "  (provider) => provider.slug,",
            ");",
            "",
        ]
    )

    MANIFEST_TS.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Fetching {LISTING_URL} ...")
    html = fetch_text(LISTING_URL)
    providers = parse_providers(html)
    print(f"Found {len(providers)} providers")

    manifest_rows: list[dict] = []

    for provider in providers:
        slug = provider["slug"]
        source_url = provider.get("sourceUrl")

        if not source_url:
            logo_file = f"{slug}.placeholder.svg"
            logo_path = OUT_DIR / logo_file
            logo_path.write_text(CAREER_PLACEHOLDER_SVG, encoding="utf-8")
            manifest_rows.append(
                {
                    **provider,
                    "logoFile": logo_file,
                    "logoType": "external",
                    "sourceUrl": "",
                    "isPlaceholder": True,
                }
            )
            print(f"  placeholder {slug}")
            continue

        download_url = upgrade_favicon(source_url)
        ext = ext_for_url(download_url)
        logo_file = f"{slug}.{ext}"
        logo_path = OUT_DIR / logo_file

        try:
            logo_path.write_bytes(fetch(download_url))
            print(f"  saved {logo_file}")
        except Exception as exc:  # noqa: BLE001
            if download_url != source_url:
                try:
                    logo_path.write_bytes(fetch(source_url))
                    print(f"  saved {logo_file} (fallback sz=64)")
                except Exception as retry_exc:  # noqa: BLE001
                    print(f"  FAILED {slug}: {retry_exc}", file=sys.stderr)
                    continue
            else:
                print(f"  FAILED {slug}: {exc}", file=sys.stderr)
                continue

        manifest_rows.append(
            {
                **provider,
                "logoFile": logo_file,
                "logoType": provider["logoType"] or classify_logo(source_url),
                "sourceUrl": source_url,
            }
        )

    snapshot_path = OUT_DIR / "manifest.snapshot.json"
    snapshot_path.write_text(
        json.dumps(manifest_rows, indent=2), encoding="utf-8"
    )
    write_manifest(manifest_rows)
    print(f"Wrote {len(manifest_rows)} entries to {MANIFEST_TS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
